# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8080
#    servlet:
#        # 应用的访问路径
#        context-path: /
    ssl:
        key-store: classpath:weixin.pfx
        key-store-password: Rp4mb81G
#        keyStoreType: PKCS12
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        # Tomcat启动初始化的线程数，默认值25
        threads:
            max: 800
            min-spare: 30

# 分页配置
pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
    reasonable: true
    params: count=countSql

markerhub:
    jwt:
        secret: 76d9fab95eb4dc698461e89b26fbf940
        expire: 604800
        header: Authorization

mybatis:
    # 搜索指定包别名
    typeAliasesPackage: qcyw.xchqcyws.entity #业务实体包和用户权限实体包
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/mapper/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/qcyw_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: qcyw2022
    jpa:
        database: mysql
        show-sql: true
    # redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password:
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
    servlet:
        multipart: #文件上传的配置
            max-file-size: 30MB #设置单个文件大小，MaxUploadSizeLimitExceededException 上传文件大于默认的限制 （MultipartProperties.java）
            max-request-size: 80MB #设置单次请求文件的总大小
    mvc:
        static-path-pattern: /**



